spring.application.name=job-x-hunter

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jobxhunterdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

adzuna.app-id=${ADZUNA_APP_ID}
adzuna.app-key=${ADZUNA_APP_KEY}
adzuna.country-code=${ADZUNA_COUNTRY_CODE:de}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml