spring.application.name=job-x-hunter
spring.datasource.url=jdbc:postgresql://localhost:5432/jobxhunterdb
spring.datasource.username=postgres
spring.datasource.password=123123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml