spring.application.name=job-x-hunter
spring.datasource.url=jdbc:postgresql://localhost:5432/jobxhunterdb
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true